# -*- coding: utf-8 -*-
"""Single source of truth for the project landing pages.

Prices come from "Sales Availability 1 Oct 2026" (column Grand Total = full price before
any discount). Update the numbers here and run:  python3 tools/build.py
"""

SITE = {
    "domain": "https://viberealestatre.com",
    "brand": "VIBE Real Estate",
    "gtm": "GTM-PVRH422L",
    "wa": "201006140168",
    "tel": "01006140168",
    "tel_intl": "+201006140168",
    # Google Apps Script web-app URL (tools/apps-script/Code.gs). Leads are NOT stored until this is set.
    "endpoint": "",
}

# Order = order of the "other projects" carousel.
PROJECTS = {
    "px": {
        "name": "PX",                      # value sent to the sheet / dataLayer
        "title": "PX Compound",            # display name (English in both languages)
        "ready": True,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 13144000,
        "down": 5, "years": 10,
        "discount": {"pct": 40, "years": 6},
        "delivery": "2028",
        "types": {"ar": ["شقق", "تاون هاوس", "فيلات"], "en": ["Apartments", "Town Houses", "Villas"]},
        "img": "px", "hero": "hero", "about_img": "view", "card": "hero",
        "hero_sub": {
            "ar": "على أعلى نقطة في بالم هيلز أكتوبر — شقق وتاون هاوس وفيلات من Palm Hills Developments",
            "en": "On the highest point of Palm Hills October — apartments, town houses and villas by Palm Hills Developments",
        },
        "seo": {
            "ar": {
                "title": "PX بالم هيلز أكتوبر | أسعار وخطط سداد PX Compound 2026 – VIBE Real Estate",
                "desc": "كمبوند PX من بالم هيلز في أكتوبر: شقق وتاون هاوس بمقدم 5% وتقسيط حتى 10 سنوات، وخصم يصل إلى 40%. الأسعار تبدأ من 13,144,000 جنيه. اعرف الوحدات المتاحة الآن.",
            },
            "en": {
                "title": "PX Palm Hills October | PX Compound Prices & Payment Plans 2026 – VIBE Real Estate",
                "desc": "PX by Palm Hills in 6th of October: apartments and town houses with 5% down payment, up to 10 years installments and up to 40% discount. Prices from EGP 13,144,000.",
            },
        },
        "about": {
            "ar": [
                "PX هو أحدث مشاريع Palm Hills Developments في غرب القاهرة، على أعلى نقطة في بالم هيلز أكتوبر، وده اللي بيدّي وحداته إطلالات مفتوحة على المنطقة كلها.",
                "المشروع على مساحة حوالي 370 فدان، والماستر بلان من تصميم Chapman Taylor العالمية، ومقسّم لمناطق سكنية مختلفة بين الشقق والتاون هاوس، مع نادي ومنطقة تجارية ومسارات مشي جوه الكمبوند.",
            ],
            "en": [
                "PX is Palm Hills Developments' newest community in West Cairo, set on the highest point of Palm Hills October — which gives its homes open views across the whole area.",
                "The project spans around 370 feddans with a master plan by Chapman Taylor, split into residential zones of apartments and town houses, with a clubhouse, a commercial hub and walking trails inside the compound.",
            ],
        },
        "facts": [
            {"v": "370", "ar": "فدان مساحة المشروع", "en": "feddans total area"},
            {"v": "2028", "ar": "بداية الاستلام", "en": "delivery starts"},
            {"v": "5%", "ar": "مقدم التعاقد", "en": "down payment"},
        ],
        "features": [
            {"ic": "mountain", "ar": ("أعلى نقطة في المنطقة", "إطلالات بانورامية مفتوحة من معظم الوحدات."),
             "en": ("Highest point in the area", "Open panoramic views from most homes.")},
            {"ic": "compass", "ar": ("ماستر بلان عالمي", "تصميم Chapman Taylor بمناطق سكنية منفصلة ومساحات مفتوحة."),
             "en": ("International master plan", "Designed by Chapman Taylor with distinct residential zones.")},
            {"ic": "dumbbell", "ar": ("كلوب هاوس ونادي رياضي", "جيم وملاعب ومرافق ترفيهية جوه المشروع."),
             "en": ("Clubhouse & sports", "Gym, courts and leisure facilities inside the project.")},
            {"ic": "store", "ar": ("منطقة تجارية", "محلات ومطاعم وكافيهات على بعد خطوات من بيتك."),
             "en": ("Commercial hub", "Retail, dining and cafés a short walk from home.")},
            {"ic": "bicycle", "ar": ("مسارات مشي ودراجات", "تراكات وسط مساحات خضراء ومسطحات مائية."),
             "en": ("Jogging & cycling trails", "Tracks running through greenery and water features.")},
            {"ic": "shield", "ar": ("أمن وبوابات 24 ساعة", "كمبوند مغلق بحراسة وكاميرات مراقبة."),
             "en": ("24/7 gated security", "A gated community with guards and CCTV.")},
        ],
        "units": [
            {"name": "1 Bedroom Apartment", "sub": {"ar": "شقة غرفة نوم واحدة", "en": "One-bedroom apartment"},
             "area": "60 – 78", "price": 13144000, "badges": ["Typical", "Penthouse"], "imgs": ["hero", "view"]},
            {"name": "2 Bedroom Apartment", "sub": {"ar": "شقة غرفتين نوم", "en": "Two-bedroom apartment"},
             "area": "113 – 140", "price": 19809000, "badges": ["Typical", "Garden", "Penthouse"], "imgs": ["view", "hero"]},
            {"name": "3 Bedroom Apartment", "sub": {"ar": "شقة 3 غرف نوم", "en": "Three-bedroom apartment"},
             "area": "144 – 172", "price": 25419000, "badges": ["Typical", "Garden"], "imgs": ["hero", "view"]},
            {"name": "Town House", "sub": {"ar": "تاون هاوس — أرض من 212 م²", "en": "Town house — land from 212 m²"},
             "area": "201 – 214", "price": 28528000, "badges": ["Middle", "Corner"], "imgs": ["view", "hero"]},
        ],
        # New launch inside PX — not in the availability sheet. Source: palmhillsdev.com/px-by-palm-hills
        "launch": {
            "name": "Palm Gardens",
            "intro": {
                "ar": "مرحلة جديدة جوه PX من التاون هاوس المتشطب بالكامل والفيلات المستقلة، على ارتفاع 128 متر فوق سطح البحر.",
                "en": "A new phase inside PX: fully finished town houses and standalone villas, set 128 m above sea level.",
            },
            "down": 5, "years": "7.5",
            "units": [
                {"name": "Townhouse Middle", "sub": {"ar": "3 غرف نوم — غرفة ماستر + ناني", "en": "3 bedrooms — 1 master + nanny room"},
                 "bua": "201", "land": "212", "price": 32638000, "finish": "ff", "imgs": ["view", "hero"]},
                {"name": "Townhouse Corner", "sub": {"ar": "3 غرف نوم — غرفة ماستر + ناني", "en": "3 bedrooms — 1 master + nanny room"},
                 "bua": "211", "land": "216", "price": 34500000, "finish": "ff", "imgs": ["hero", "view"]},
                {"name": "Villa 4", "sub": {"ar": "4 غرف نوم — 2 ماستر + ناني وسائق", "en": "4 bedrooms — 2 master + nanny & driver"},
                 "bua": "240", "land": "282", "price": 37000000, "finish": "cs", "imgs": ["view", "hero"]},
                {"name": "Villa 3", "sub": {"ar": "4 غرف نوم — 2 ماستر + ناني وسائق", "en": "4 bedrooms — 2 master + nanny & driver"},
                 "bua": "246", "land": "299", "price": 38800000, "finish": "cs", "imgs": ["hero", "view"]},
                {"name": "Villa 1", "sub": {"ar": "4 غرف نوم — 3 ماستر + أسانسير", "en": "4 bedrooms — 3 master + elevator"},
                 "bua": "314", "land": "420 – 470", "price": 53000000, "finish": "cs", "imgs": ["view", "hero"]},
                {"name": "Villa 5", "sub": {"ar": "6 غرف نوم ماستر + أسانسير", "en": "6 master bedrooms + elevator"},
                 "bua": "428", "land": "545 – 596", "price": None, "finish": "cs", "imgs": ["hero", "view"]},
            ],
        },
        "location": {
            "text": {
                "ar": "PX في قلب بالم هيلز أكتوبر، ومتصل بأهم محاور غرب القاهرة، وحواليه كمبوندات بالم هيلز التانية زي ذا كراون وبالم باركس.",
                "en": "PX sits at the heart of Palm Hills October, connected to West Cairo's main roads and surrounded by Palm Hills communities such as The Crown and Palm Parks.",
            },
            "points": [
                {"b": {"ar": "وصلة دهشور", "en": "Dahshur Link"}, "s": {"ar": "مدخل مباشر للمشروع", "en": "Direct access to the project"}},
                {"b": {"ar": "محور 26 يوليو", "en": "26th of July Axis"}, "s": {"ar": "ربط سريع بالقاهرة والشيخ زايد", "en": "Fast link to Cairo and Sheikh Zayed"}},
                {"b": {"ar": "طريق الواحات", "en": "Wahat Road"}, "s": {"ar": "أقرب طريق للمحاور الجنوبية", "en": "Closest route to the southern corridors"}},
                {"b": {"ar": "Mall of Egypt", "en": "Mall of Egypt"}, "s": {"ar": "أقرب مركز تسوق وترفيه", "en": "Nearest shopping & entertainment"}},
                {"b": {"ar": "المتحف المصري الكبير", "en": "Grand Egyptian Museum"}, "s": {"ar": "وأهرامات الجيزة", "en": "and the Giza Pyramids"}},
                {"b": {"ar": "مدينة الإنتاج الإعلامي", "en": "Media Production City"}, "s": {"ar": "وجامعات ومدارس أكتوبر", "en": "plus October's universities & schools"}},
            ],
            "map": "masterplan",
            "map_cap": {"ar": "الماستر بلان — اضغط للتكبير", "en": "Master plan — tap to enlarge"},
        },
        "gallery": [
            {"img": "hero", "cap": {"ar": "PX Compound — واجهات المباني", "en": "PX Compound — building façades"}},
            {"img": "view", "cap": {"ar": "PX Compound — فيو المشروع", "en": "PX Compound — project view"}},
            {"img": "masterplan", "cap": {"ar": "PX Compound — الماستر بلان", "en": "PX Compound — master plan"}},
        ],
    },
    "palm-parks": {
        "name": "Palm Parks", "title": "Palm Parks", "ready": True,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 17807000, "down": 5, "years": 8, "discount": None, "delivery": "2029",
        "types": {"ar": ["شقق"], "en": ["Apartments"]},
        "img": "palm-parks", "hero": "hero", "about_img": "view", "card": "card",
        "hero_sub": {
            "ar": "شقق في مجتمع سكني هادي عند وصلة دهشور — من Palm Hills Developments",
            "en": "Apartments in a quiet boutique community off the Dahshur Link — by Palm Hills Developments",
        },
        "seo": {
            "ar": {"title": "Palm Parks بالم هيلز أكتوبر | أسعار شقق بالم باركس 2026 – VIBE Real Estate",
                   "desc": "شقق Palm Parks من بالم هيلز في أكتوبر عند وصلة دهشور: مقدم 5% وتقسيط حتى 8 سنوات، والأسعار تبدأ من 17,807,000 جنيه. اعرف الوحدات المتاحة الآن."},
            "en": {"title": "Palm Parks Palm Hills October | Apartment Prices & Payment Plans 2026 – VIBE Real Estate",
                   "desc": "Palm Parks by Palm Hills in 6th of October, off the Dahshur Link: apartments with 5% down payment and up to 8 years installments. Prices from EGP 17,807,000."},
        },
        "about": {
            "ar": ["Palm Parks مجتمع سكني من Palm Hills Developments في غرب القاهرة، عند وصلة دهشور مباشرة، ومصمم كحي سكني هادي بكثافة قليلة ومساحات مفتوحة بين المباني.",
                   "المشروع كله شقق بمساحات عملية، وجواه كلوب هاوس وحمامات سباحة ومنطقة تجارية، والوحدات المتاحة حاليًا محدودة."],
            "en": ["Palm Parks is a Palm Hills Developments community in West Cairo, right off the Dahshur Link, designed as a quiet low-density neighbourhood with open space between buildings.",
                   "The project is all apartments with practical layouts, with a clubhouse, swimming pools and a commercial area inside. Only a limited number of units is currently available."],
        },
        "facts": [
            {"v": "2029", "ar": "الاستلام", "en": "delivery"},
            {"v": "8", "ar": "سنوات تقسيط", "en": "years installments"},
            {"v": "5%", "ar": "مقدم التعاقد", "en": "down payment"},
        ],
        "features": [
            {"ic": "leaf", "ar": ("حي سكني هادي", "كثافة قليلة ومساحات خضراء بين المباني."), "en": ("A quiet neighbourhood", "Low density with greenery between buildings.")},
            {"ic": "swim", "ar": ("حمامات سباحة", "حمامات سباحة ومسطحات مائية جوه المشروع."), "en": ("Swimming pools", "Pools and water features inside the project.")},
            {"ic": "dumbbell", "ar": ("كلوب هاوس وجيم", "نادي اجتماعي وجيم وملاعب رياضية."), "en": ("Clubhouse & gym", "A social club, gym and sports courts.")},
            {"ic": "store", "ar": ("منطقة تجارية", "محلات ومطاعم لخدمة السكان."), "en": ("Commercial area", "Shops and restaurants serving residents.")},
            {"ic": "child", "ar": ("مناطق للأطفال", "ملاعب ومساحات لعب آمنة."), "en": ("Kids' areas", "Safe playgrounds and play spaces.")},
            {"ic": "shield", "ar": ("أمن وبوابات 24 ساعة", "كمبوند مغلق بحراسة على مدار اليوم."), "en": ("24/7 gated security", "A gated community guarded around the clock.")},
        ],
        "units": [
            {"name": "3 Bedroom Apartment", "sub": {"ar": "شقة 3 غرف نوم", "en": "Three-bedroom apartment"},
             "area": "169 – 170", "price": 17807000, "badges": ["Typical"], "imgs": ["hero", "view"]},
            {"name": "2 Bedroom Apartment with Garden", "sub": {"ar": "شقة غرفتين نوم بجاردن", "en": "Two-bedroom garden apartment"},
             "area": "132", "price": 18202000, "badges": ["Garden"], "imgs": ["view", "hero"]},
            {"name": "3 Bedroom Apartment with Garden", "sub": {"ar": "شقة 3 غرف نوم بجاردن", "en": "Three-bedroom garden apartment"},
             "area": "170", "price": 21719000, "badges": ["Garden"], "imgs": ["hero", "view"]},
        ],
        "location": {
            "text": {"ar": "Palm Parks عند وصلة دهشور مباشرة في غرب القاهرة، قريب من مدينة الإنتاج الإعلامي وأهم مراكز التسوق في أكتوبر.",
                     "en": "Palm Parks sits right off the Dahshur Link in West Cairo, close to Media Production City and October's main shopping destinations."},
            "points": [
                {"b": {"ar": "5 دقائق", "en": "5 min"}, "s": {"ar": "مدينة الإنتاج الإعلامي", "en": "Media Production City"}},
                {"b": {"ar": "13 دقيقة", "en": "13 min"}, "s": {"ar": "Mall of Arabia", "en": "Mall of Arabia"}},
                {"b": {"ar": "14 دقيقة", "en": "14 min"}, "s": {"ar": "Palm Central", "en": "Palm Central"}},
                {"b": {"ar": "15 دقيقة", "en": "15 min"}, "s": {"ar": "القرية الذكية", "en": "Smart Village"}},
                {"b": {"ar": "16 دقيقة", "en": "16 min"}, "s": {"ar": "Palm Hills Club", "en": "Palm Hills Club"}},
                {"b": {"ar": "30 دقيقة", "en": "30 min"}, "s": {"ar": "وسط القاهرة", "en": "Downtown Cairo"}},
            ],
            "map": "masterplan", "map_cap": {"ar": "الماستر بلان — اضغط للتكبير", "en": "Master plan — tap to enlarge"},
        },
        "gallery": [
            {"img": "hero", "cap": {"ar": "Palm Parks — فيو المشروع", "en": "Palm Parks — project view"}},
            {"img": "view", "cap": {"ar": "Palm Parks — المباني والمسطحات المائية", "en": "Palm Parks — buildings and water features"}},
            {"img": "masterplan", "cap": {"ar": "Palm Parks — الماستر بلان", "en": "Palm Parks — master plan"}},
        ],
    },
    "crown-extension": {
        "name": "The Crown Extension", "title": "Crown Extension", "ready": True,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 30521000, "down": 5, "years": 8, "discount": {"pct": 30, "years": 5}, "delivery": "2030",
        "types": {"ar": ["Family Home", "توين هاوس"], "en": ["Family Homes", "Twin Houses"]},
        "img": "crown-extension", "hero": "hero", "about_img": "unit", "card": "card",
        "hero_sub": {
            "ar": "Family Homes وتوين هاوس في امتداد The Crown بقلب بالم هيلز أكتوبر",
            "en": "Family homes and twin houses in the extension of The Crown, at the heart of Palm Hills October",
        },
        "seo": {
            "ar": {"title": "Crown Extension بالم هيلز أكتوبر | أسعار ذا كراون 2026 – VIBE Real Estate",
                   "desc": "The Crown Extension من بالم هيلز في أكتوبر: Family Homes وتوين هاوس بمقدم 5% وتقسيط حتى 8 سنوات، وخصم يصل إلى 30%. الأسعار تبدأ من 30,521,000 جنيه."},
            "en": {"title": "Crown Extension Palm Hills October | Prices & Payment Plans 2026 – VIBE Real Estate",
                   "desc": "The Crown Extension by Palm Hills in 6th of October: family homes and twin houses with 5% down payment, up to 8 years installments and up to 30% discount. From EGP 30,521,000."},
        },
        "about": {
            "ar": ["Crown Extension هو امتداد كمبوند The Crown من Palm Hills Developments في قلب بالم هيلز أكتوبر، بالقرب من محور 26 يوليو وطريق مصر إسكندرية الصحراوي.",
                   "المرحلة فيها Family Homes بمساحات كبيرة — بجاردن خاصة أو بنتهاوس — وعدد محدود من التوين هاوس، وسط كثافة بنائية قليلة ومساحات خضراء واسعة."],
            "en": ["Crown Extension is the extension of The Crown by Palm Hills Developments at the heart of Palm Hills October, close to the 26th of July Axis and the Cairo–Alexandria Desert Road.",
                   "The phase offers spacious family homes — with a private garden or a penthouse — and a limited number of twin houses, in a low-density setting with wide green areas."],
        },
        "facts": [
            {"v": "30%", "ar": "خصم يصل إلى", "en": "discount up to"},
            {"v": "2030", "ar": "الاستلام", "en": "delivery"},
            {"v": "5%", "ar": "مقدم التعاقد", "en": "down payment"},
        ],
        "features": [
            {"ic": "expand", "ar": ("مساحات واسعة", "وحدات تبدأ من 217 م² بجاردن أو بنتهاوس."), "en": ("Generous sizes", "Homes from 217 m² with a garden or penthouse.")},
            {"ic": "leaf", "ar": ("مساحات خضراء", "كثافة بنائية قليلة ومسطحات خضراء واسعة."), "en": ("Green open spaces", "Low density with wide landscaped areas.")},
            {"ic": "dumbbell", "ar": ("قريب من Palm Hills Club", "نادي بالم هيلز بملاعبه وحمامات السباحة."), "en": ("Near Palm Hills Club", "Courts, pools and facilities of Palm Hills Club.")},
            {"ic": "store", "ar": ("خدمات ومطاعم", "Palm Central ومناطق تجارية على بعد دقائق."), "en": ("Retail & dining", "Palm Central and retail areas minutes away.")},
            {"ic": "grad", "ar": ("مدارس دولية قريبة", "أهم مدارس وجامعات أكتوبر في محيط المشروع."), "en": ("International schools nearby", "October's leading schools and universities close by.")},
            {"ic": "shield", "ar": ("أمن وبوابات 24 ساعة", "كمبوند مغلق بحراسة على مدار اليوم."), "en": ("24/7 gated security", "A gated community guarded around the clock.")},
        ],
        "units": [
            {"name": "Family Home with Penthouse", "sub": {"ar": "Family Home ببنتهاوس", "en": "Family home with penthouse"},
             "area": "223", "price": 30521000, "badges": ["Penthouse"], "imgs": ["hero", "unit"]},
            {"name": "Family Home with Garden", "sub": {"ar": "Family Home بجاردن خاصة", "en": "Family home with private garden"},
             "area": "217", "price": 33164000, "badges": ["Garden"], "imgs": ["unit", "hero"]},
            {"name": "Twin House", "sub": {"ar": "توين هاوس — عدد محدود", "en": "Twin house — limited availability"},
             "bua": "226", "land": "281", "price": 38213000, "imgs": ["hero", "unit"]},
        ],
        "location": {
            "text": {"ar": "Crown Extension في قلب بالم هيلز أكتوبر، بالقرب من محور 26 يوليو وطريق مصر إسكندرية الصحراوي والطريق الدائري.",
                     "en": "Crown Extension is at the heart of Palm Hills October, near the 26th of July Axis, the Cairo–Alexandria Desert Road and the Ring Road."},
            "points": [
                {"b": {"ar": "5 دقائق", "en": "5 min"}, "s": {"ar": "الطريق الدائري", "en": "Ring Road"}},
                {"b": {"ar": "8 دقائق", "en": "8 min"}, "s": {"ar": "Palm Central", "en": "Palm Central"}},
                {"b": {"ar": "10 دقائق", "en": "10 min"}, "s": {"ar": "نادي الجزيرة", "en": "Gezira Sporting Club"}},
                {"b": {"ar": "12 دقيقة", "en": "12 min"}, "s": {"ar": "محور 26 يوليو", "en": "26th of July Axis"}},
                {"b": {"ar": "15 دقيقة", "en": "15 min"}, "s": {"ar": "Palm Hills Club", "en": "Palm Hills Club"}},
                {"b": {"ar": "17 دقيقة", "en": "17 min"}, "s": {"ar": "Mall of Egypt", "en": "Mall of Egypt"}},
            ],
            "map": "masterplan", "map_cap": {"ar": "الماستر بلان — اضغط للتكبير", "en": "Master plan — tap to enlarge"},
        },
        "gallery": [
            {"img": "hero", "cap": {"ar": "Crown Extension — المشروع", "en": "Crown Extension — the project"}},
            {"img": "unit", "cap": {"ar": "Crown Extension — الوحدات", "en": "Crown Extension — the homes"}},
            {"img": "masterplan", "cap": {"ar": "Crown Extension — الماستر بلان", "en": "Crown Extension — master plan"}},
        ],
    },
    "palm-hills-one": {
        "name": "Palm Hills One", "title": "Palm Hills One", "ready": True,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 47549000, "down": 5, "years": 8, "discount": None, "delivery": "2030",
        "types": {"ar": ["تاون هاوس", "توين هاوس", "فيلات"], "en": ["Town Houses", "Twin Houses", "Villas"]},
        "img": "palm-hills-one", "hero": "hero", "about_img": "hero", "card": "card",
        "hero_sub": {
            "ar": "فيلات وتوين هاوس وتاون هاوس في موقع The Hill — مجتمع فيلات فقط من Palm Hills Developments",
            "en": "Villas, twin houses and town houses at The Hill — a villas-only community by Palm Hills Developments",
        },
        "seo": {
            "ar": {"title": "Palm Hills One أكتوبر | أسعار فيلات بالم هيلز وان 2026 – VIBE Real Estate",
                   "desc": "Palm Hills One من بالم هيلز في غرب القاهرة: فيلات وتوين هاوس وتاون هاوس بمقدم 5% وتقسيط حتى 8 سنوات. الأسعار تبدأ من 47,549,000 جنيه. اعرف الوحدات المتاحة."},
            "en": {"title": "Palm Hills One October | Villa Prices & Payment Plans 2026 – VIBE Real Estate",
                   "desc": "Palm Hills One by Palm Hills in West Cairo: villas, twin houses and town houses with 5% down payment and up to 8 years installments. Prices from EGP 47,549,000."},
        },
        "about": {
            "ar": ["Palm Hills One مجتمع فيلات من Palm Hills Developments في موقع The Hill بقلب غرب القاهرة، متاخم لبالم هيلز أكتوبر وعلى بعد دقائق من طريق مصر إسكندرية الصحراوي.",
                   "المشروع فيلات فقط: تاون هاوس وتوين هاوس وفيلات مستقلة بـ6 نماذج مختلفة، على أراضي من 350 م² وحتى 1,500 م²."],
            "en": ["Palm Hills One is a villa community by Palm Hills Developments at The Hill in the heart of West Cairo, adjacent to Palm Hills October and minutes from the Cairo–Alexandria Desert Road.",
                   "It is villas only: town houses, twin houses and standalone villas in six different models, on plots from 350 m² up to 1,500 m²."],
        },
        "facts": [
            {"v": "1,500", "ar": "م² أكبر مساحة أرض", "en": "m² largest plot"},
            {"v": "2030", "ar": "الاستلام", "en": "delivery"},
            {"v": "5%", "ar": "مقدم التعاقد", "en": "down payment"},
        ],
        "features": [
            {"ic": "house", "ar": ("مجتمع فيلات فقط", "تاون وتوين وفيلات مستقلة من غير عمارات."), "en": ("Villas only", "Town, twin and standalone villas — no apartment blocks.")},
            {"ic": "mountain", "ar": ("موقع The Hill", "موقع مرتفع في قلب غرب القاهرة."), "en": ("The Hill location", "An elevated site in the heart of West Cairo.")},
            {"ic": "expand", "ar": ("أراضي واسعة", "مساحات أراضي من 350 م² وحتى 1,500 م²."), "en": ("Large plots", "Land areas from 350 m² up to 1,500 m².")},
            {"ic": "compass", "ar": ("6 نماذج فيلات", "اختيارات متعددة حسب المساحة والميزانية."), "en": ("6 villa models", "A range of options by size and budget.")},
            {"ic": "road", "ar": ("قريب من المحاور الرئيسية", "دقائق من طريق مصر إسكندرية الصحراوي."), "en": ("Close to main roads", "Minutes from the Cairo–Alexandria Desert Road.")},
            {"ic": "shield", "ar": ("أمن وخصوصية", "كمبوند مغلق بحراسة على مدار اليوم."), "en": ("Security & privacy", "A gated community guarded around the clock.")},
        ],
        "units": [
            {"name": "Town House", "sub": {"ar": "تاون هاوس ميدل", "en": "Middle town house"},
             "bua": "358", "land": "350", "price": 47549000, "imgs": ["hero"]},
            {"name": "Twin House", "sub": {"ar": "توين هاوس — نموذجين", "en": "Twin house — two models"},
             "bua": "340 – 358", "land": "370 – 430", "price": 57950000, "imgs": ["hero"]},
            {"name": "Standalone Villa", "sub": {"ar": "فيلا مستقلة — 6 نماذج", "en": "Standalone villa — six models"},
             "bua": "195 – 673", "land": "451 – 1,500", "price": 86087000, "imgs": ["hero"]},
        ],
        "location": {
            "text": {"ar": "Palm Hills One في موقع The Hill بقلب غرب القاهرة، متاخم لبالم هيلز أكتوبر وقريب من كل خدماتها.",
                     "en": "Palm Hills One is at The Hill in the heart of West Cairo, adjacent to Palm Hills October and close to all its services."},
            "points": [
                {"b": {"ar": "5 دقائق", "en": "5 min"}, "s": {"ar": "طريق مصر إسكندرية الصحراوي", "en": "Cairo–Alexandria Desert Road"}},
                {"b": {"ar": "بالم هيلز أكتوبر", "en": "Palm Hills October"}, "s": {"ar": "متاخم للمشروع مباشرة", "en": "Directly adjacent"}},
                {"b": {"ar": "Palm Hills Club", "en": "Palm Hills Club"}, "s": {"ar": "النادي والملاعب", "en": "Club and sports facilities"}},
                {"b": {"ar": "Palm Central", "en": "Palm Central"}, "s": {"ar": "مطاعم وخدمات يومية", "en": "Dining and daily services"}},
                {"b": {"ar": "محور 26 يوليو", "en": "26th of July Axis"}, "s": {"ar": "ربط سريع بالقاهرة وزايد", "en": "Fast link to Cairo and Zayed"}},
                {"b": {"ar": "Mall of Arabia", "en": "Mall of Arabia"}, "s": {"ar": "تسوق وترفيه", "en": "Shopping and entertainment"}},
            ],
            "map": None,
        },
        "gallery": [],
    },
    "bamboo-iii": {
        "name": "Bamboo III", "title": "Bamboo III", "ready": True,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 27457000, "down": 5, "years": 10, "discount": None, "delivery": "2029",
        "types": {"ar": ["Family Home", "تاون هاوس"], "en": ["Family Homes", "Town Houses"]},
        "img": "bamboo-iii", "hero": "hero", "about_img": "lagoon", "card": "card",
        "hero_sub": {
            "ar": "Family Homes وتاون هاوس على محور 26 يوليو — المرحلة الثالثة من Bamboo بالم هيلز",
            "en": "Family homes and town houses on the 26th of July Axis — the third phase of Bamboo by Palm Hills",
        },
        "seo": {
            "ar": {"title": "Bamboo III بالم هيلز أكتوبر | أسعار بامبو 3 وخطط السداد 2026 – VIBE Real Estate",
                   "desc": "Bamboo III من بالم هيلز في أكتوبر على محور 26 يوليو: Family Homes وتاون هاوس بمقدم 5% وتقسيط حتى 10 سنوات. الأسعار تبدأ من 27,457,000 جنيه."},
            "en": {"title": "Bamboo III Palm Hills October | Prices & Payment Plans 2026 – VIBE Real Estate",
                   "desc": "Bamboo III by Palm Hills in 6th of October on the 26th of July Axis: family homes and town houses with 5% down payment and up to 10 years installments. From EGP 27,457,000."},
        },
        "about": {
            "ar": ["Bamboo III هي المرحلة الثالثة من Bamboo من Palm Hills Developments، جوه بالم هيلز أكتوبر بالقرب من نادي الجزيرة، ومطلّة على محور 26 يوليو.",
                   "المشروع على حوالي 56 فدان، منها لاجونز ومسطحات مائية ومساحات خضراء واسعة، والوحدات Family Homes بجاردن أو بنتهاوس وتاون هاوس ميدل وكورنر — كلها متشطبة بالكامل."],
            "en": ["Bamboo III is the third phase of Bamboo by Palm Hills Developments, inside Palm Hills October near Gezira Club and overlooking the 26th of July Axis.",
                   "The project covers around 56 acres with lagoons, water features and wide green areas. Homes are family homes with a garden or penthouse plus middle and corner town houses — all fully finished."],
        },
        "facts": [
            {"v": "10", "ar": "سنوات تقسيط", "en": "years installments"},
            {"v": "2029", "ar": "استلام متشطب بالكامل", "en": "fully finished delivery"},
            {"v": "5%", "ar": "مقدم التعاقد", "en": "down payment"},
        ],
        "features": [
            {"ic": "road", "ar": ("على محور 26 يوليو", "وصول مباشر لأهم مناطق غرب القاهرة."), "en": ("On the 26th of July Axis", "Direct access to West Cairo's key districts.")},
            {"ic": "swim", "ar": ("لاجونز ومسطحات مائية", "أكتر من 10,000 م² مسطحات مائية جوه المشروع."), "en": ("Lagoons & water features", "Over 10,000 m² of water features inside the project.")},
            {"ic": "key", "ar": ("تشطيب كامل", "كل الوحدات بتتسلم متشطبة بالكامل."), "en": ("Fully finished", "Every home is delivered fully finished.")},
            {"ic": "run", "ar": ("مسارات مشي وجري", "تراكات وسط مساحات خضراء."), "en": ("Walking & jogging tracks", "Trails running through landscaped greenery.")},
            {"ic": "store", "ar": ("محلات ومطاعم", "خدمات تجارية جوه المشروع."), "en": ("Retail & dining", "Commercial services inside the project.")},
            {"ic": "shield", "ar": ("أمن وبوابات 24 ساعة", "كمبوند مغلق بحراسة وكاميرات."), "en": ("24/7 gated security", "A gated community with guards and CCTV.")},
        ],
        "units": [
            {"name": "Family Home with Garden", "sub": {"ar": "Family Home بجاردن خاصة", "en": "Family home with private garden"},
             "area": "182", "price": 27457000, "badges": ["Garden"], "finish": "ff", "imgs": ["hero", "lagoon"]},
            {"name": "Family Home with Penthouse", "sub": {"ar": "Family Home ببنتهاوس", "en": "Family home with penthouse"},
             "area": "191 – 192", "price": 28750000, "badges": ["Penthouse"], "finish": "ff", "imgs": ["lagoon", "hero"]},
            {"name": "Town House Middle", "sub": {"ar": "تاون هاوس ميدل", "en": "Middle town house"},
             "bua": "221", "land": "249 – 254", "price": 34342000, "finish": "ff", "imgs": ["facade", "hero"]},
            {"name": "Town House Corner", "sub": {"ar": "تاون هاوس كورنر", "en": "Corner town house"},
             "bua": "222", "land": "249 – 254", "price": 35303000, "finish": "ff", "imgs": ["facade", "lagoon"]},
        ],
        "location": {
            "text": {"ar": "Bamboo III على محور 26 يوليو في أكتوبر، قريب من أكبر مولات غرب القاهرة والجامعات والنوادي.",
                     "en": "Bamboo III is on the 26th of July Axis in 6th of October, close to West Cairo's largest malls, universities and clubs."},
            "points": [
                {"b": {"ar": "10 دقائق", "en": "10 min"}, "s": {"ar": "Mall of Arabia", "en": "Mall of Arabia"}},
                {"b": {"ar": "12 دقيقة", "en": "12 min"}, "s": {"ar": "Mall of Egypt", "en": "Mall of Egypt"}},
                {"b": {"ar": "15 دقيقة", "en": "15 min"}, "s": {"ar": "جامعة 6 أكتوبر", "en": "October 6 University"}},
                {"b": {"ar": "18 دقيقة", "en": "18 min"}, "s": {"ar": "نادي الجزيرة", "en": "Gezira Sporting Club"}},
                {"b": {"ar": "20 دقيقة", "en": "20 min"}, "s": {"ar": "Palm Hills Club", "en": "Palm Hills Club"}},
                {"b": {"ar": "25 دقيقة", "en": "25 min"}, "s": {"ar": "مطار سفنكس الدولي", "en": "Sphinx International Airport"}},
            ],
            "map": None,
        },
        "gallery": [
            {"img": "hero", "cap": {"ar": "Bamboo III — اللاجون والمباني", "en": "Bamboo III — lagoon and buildings"}},
            {"img": "lagoon", "cap": {"ar": "Bamboo III — المسطحات المائية", "en": "Bamboo III — water features"}},
            {"img": "facade", "cap": {"ar": "Bamboo III — واجهة الوحدات", "en": "Bamboo III — home façade"}},
        ],
    },
}

T = {
    "ar": {
        "dir": "rtl", "locale": "ar_EG",
        "nav": [("#units", "الوحدات والأسعار"), ("#about", "عن المشروع"), ("#location", "الموقع"), ("#gallery", "الصور"), ("#more", "مشاريع أخرى")],
        "nav_cta": "اعرف الأسعار",
        "menu": "القائمة",
        "cta_main": "تفاصيل أكثر - واتساب",
        "cta_card": "الأسعار وخطط السداد",
        "down": "مقدم", "years": "سنوات تقسيط", "from_m": "يبدأ من (مليون جنيه)",
        "offer_badge": "خصم يصل إلى {p}% مع تقسيط {y} سنوات",
        "hero_note": "الأسعار استرشادية وقابلة للتغيير حسب المطوّر",
        "about_eyebrow": "About the project", "about_h": "نبذة عن {t}", "about_p": "كل اللي محتاج تعرفه عن المشروع في دقيقة",
        "units_eyebrow": "Units & Prices", "units_h": "الوحدات المتاحة في {t}", "units_p": "اختار نوع الوحدة واعرف السعر وخطة السداد على واتساب",
        "u_area": "المساحة", "u_deliv": "الاستلام", "from": "تبدأ من", "egp": "جنيه", "sqm": "م²",
        "u_bua": "مساحة المباني", "u_land": "مساحة الأرض", "price_req": "السعر عند الطلب",
        "new_launch": "لونش جديد", "fin_ff": "متشطب بالكامل", "fin_cs": "Core & Shell",
        "launch_eyebrow": "New Launch", "launch_h": "مرحلة جديدة: {n}", "launch_pay": "مقدم {d}% وتقسيط حتى {y} سنوات",
        "units_disc": "الأسعار والوحدات المعروضة أعلاه استرشادية وقابلة للتغيير أو التحديث في أي وقت دون إشعار مسبق، حسب سياسة الشركة المطوّرة ومدى توافر الوحدات لديها. جميع الصور والمواد الترويجية تخص Palm Hills Developments وتُعرض بغرض التوضيح فقط.",
        "offer_h": "خصم يصل إلى <b>{p}%</b> مع تقسيط {y} سنوات", "offer_p": "أو مقدم {d}% وتقسيط حتى {yy} سنوات — اسأل عن الخطة الأنسب ليك.",
        "plan_h": "مقدم <b>{d}%</b> وتقسيط حتى <b>{yy} سنوات</b>", "plan_p": "اسأل عن خطة السداد الأنسب ليك وأحدث الوحدات المتاحة.",
        "offer_cta": "اعرف تفاصيل العرض",
        "loc_eyebrow": "Location", "loc_h": "موقع {t}", "loc_p": "قريب من كل اللي بتحتاجه في غرب القاهرة",
        "gal_eyebrow": "Photo Gallery", "gal_h": "معرض الصور", "gal_p": "لمحة من {t}",
        "more_eyebrow": "More Palm Hills projects", "more_h": "مشاريع بالم هيلز التانية", "more_p": "لو {t} مش الأنسب ليك، شوف باقي مشاريع بالم هيلز المتاحة",
        "more_link": "تفاصيل المشروع", "more_off": "خصم حتى {p}%",
        "final_h": "اعرف أحدث أسعار <b>{t}</b> على واتساب", "final_lead": "سجّل رقمك وهنحوّلك على واتساب في نفس اللحظة.",
        "final_points": ["الوحدات المتاحة حاليًا بالأسعار المحدّثة", "خطط السداد والخصومات السارية", "رد مباشر من مستشار عقاري"],
        "final_call": "أو كلّمنا: ", "final_form_h": "تفاصيل أكثر على واتساب",
        "f_title": "تفاصيل أكثر على واتساب", "f_sub": "اكتب اسمك ورقمك وهنحوّلك على واتساب فورًا",
        "f_name": "الاسم", "f_name_ph": "اسمك", "f_name_err": "اكتب اسمك من فضلك",
        "f_phone": "رقم الموبايل", "f_phone_err": "الرقم مش صحيح — راجع الرقم وكود الدولة",
        "f_unit": "نوع الوحدة", "f_unit_ph": "اختار نوع الوحدة", "f_unit_any": "لسه مش محدد", "f_unit_err": "اختار نوع الوحدة",
        "f_cc": "كود الدولة", "f_cc_search": "دوّر على الدولة أو الكود",
        "f_submit": "تحويل إلى واتساب", "f_sending": "جاري التحويل…",
        "f_priv": 'بتسجيلك أنت موافق على <a href="/privacy-policy" target="_blank" rel="noopener">سياسة الخصوصية</a>',
        "no_country": "مفيش نتايج", "close": "إغلاق",
        "stick_from": "يبدأ من", "stick_cta": "تفاصيل - واتساب",
        "ck_title": "نحترم خصوصيتك 🍪",
        "ck_text": 'بنستخدم ملفات تعريف الارتباط (Cookies) لتتبع الأداء وتحسين تجربتك على الموقع. للمزيد اطّلع على <a href="/privacy-policy">سياسة الخصوصية</a>.',
        "ck_short": 'بنستخدم Cookies لتحسين تجربتك. <a href="/privacy-policy">سياسة الخصوصية</a>',
        "ck_ok": "موافق، تمام", "ck_ok_short": "موافق", "ck_aria": "إشعار ملفات تعريف الارتباط",
        "ft_tag": "Connecting You to Egypt's Finest Properties",
        "ft_disc": "<strong>إخلاء مسؤولية:</strong> هذا الموقع عبارة عن منصة إعلامية وتسويقية مملوكة وتُدار بواسطة <strong>وسيط عقاري مستقل</strong>، ولسنا المطور الرسمي أو المالك لأي من المشاريع المعروضة. يهدف الموقع إلى عرض وتسويق الفرص السكنية والاستثمارية المتاحة من مطورين عقاريين مختلفين وذلك لأغراض تعريفية وتسويقية فقط. جميع الأسعار وخطط السداد والمواصفات المعروضة قابلة للتغيير من قِبل المطورين دون إشعار مسبق، والمرجع النهائي هو المطور الرسمي لكل مشروع. نلتزم بالشفافية الكاملة وبحماية خصوصية بيانات المستخدمين وعدم مشاركتها مع أي طرف ثالث دون موافقة صريحة.",
        "ft_rights": "جميع الحقوق محفوظة", "ft_about": "About Us", "ft_priv": "سياسة الخصوصية",
        "crumb_home": "الرئيسية",
        "home_seo_title": "VIBE Real Estate | مشاريع بالم هيلز في أكتوبر — أسعار وخطط سداد 2026",
        "home_seo_desc": "VIBE Real Estate — وسيط عقاري مستقل. أحدث مشاريع بالم هيلز في أكتوبر: PX وPalm Parks وCrown Extension وPalm Hills One وBamboo III، بالأسعار وخطط السداد.",
        "home_nav": [("#projects", "المشاريع"), ("#more", "وجهات أخرى"), ("#about", "عن VIBE"), ("/about-us", "About Us")],
        "home_eyebrow": "Palm Hills Developments",
        "home_h1": "مشاريع بالم هيلز في أكتوبر",
        "home_sub": "شقق وتاون هاوس وفيلات من Palm Hills Developments — بالأسعار وخطط السداد لكل مشروع",
        "home_stats": [("5", "مشاريع متاحة"), ("5%", "مقدم يبدأ من"), ("10", "سنوات تقسيط حتى")],
        "home_cta2": "شوف المشاريع",
        "home_proj_eyebrow": "Our Projects", "home_proj_h": "اختار مشروعك", "home_proj_p": "كل مشروع ليه صفحة بوحداته وأسعاره وموقعه",
        "home_more_eyebrow": "More destinations", "home_more_h": "وجهات أخرى من بالم هيلز", "home_more_p": "القاهرة الجديدة والعاصمة الإدارية والساحل الشمالي",
        "home_more": [
            {"href": "/palm-hills-projects-east", "img": "east", "title": "Palm Hills East", "tag": "شرق القاهرة", "text": "Palm Hills New Cairo و97 Hills وVDLC في العاصمة الإدارية."},
            {"href": "/hacienda-ras-al-hekma", "img": "hacienda", "title": "Hacienda Ras Al Hekma", "tag": "الساحل الشمالي", "text": "شاليهات وتوين هاوس وفيلات في رأس الحكمة."},
        ],
        "home_explore": "استكشف",
        "home_about_eyebrow": "About VIBE", "home_about_h": "بوصلتك في السوق العقاري المصري",
        "home_about": ["VIBE Real Estate وسيط عقاري مستقل، متخصص في عرض وتسويق مشاريع Palm Hills Developments في غرب وشرق القاهرة والساحل الشمالي.",
                       "بنعرض الأسعار وخطط السداد زي ما هي من المطوّر، وبنساعدك تقارن وتختار الوحدة اللي تناسب احتياجك وميزانيتك — من غير ضغط."],
        "home_about_link": "اعرف أكتر عننا",
        "home_vibe": [("V", "Vision", "رؤية واضحة للسوق واتجاهاته."), ("I", "Investment", "كل ترشيح بعقلية استثمارية."), ("B", "Brokerage", "خبرة أكتر من 20 سنة في السوق المصري."), ("E", "Excellence", "دقة في المعلومة وسرعة في الرد.")],
        "home_final_h": "مش عارف تختار؟ <b>كلّمنا على واتساب</b>", "home_final_lead": "قولنا المشروع اللي مهتم بيه وهنبعتلك الأسعار وخطط السداد.",
        "f_project": "المشروع", "f_project_ph": "اختار المشروع", "f_project_err": "اختار المشروع",
        "home_back": "الصفحة الرئيسية",
        "ty_seo_title": "شكرًا لتسجيلك – VIBE Real Estate",
        "ty_title": "شكرًا لاهتمامك", "ty_title_p": "شكرًا لاهتمامك بـ {p}",
        "ty_text": "خطوة واحدة وتوصلك التفاصيل على واتساب.",
        "ty_points": ["أحدث الأسعار والوحدات المتاحة", "خطط السداد والعروض الحالية", "مستشار عقاري يرد على كل أسئلتك"],
        "ty_title_generic": "شكرًا لزيارتك", "ty_text_generic": "تقدر تتواصل معانا على واتساب في أي وقت.",
        "ty_btn": "افتح واتساب الآن", "ty_redirecting": "هنحوّلك على واتساب خلال ثواني…",
        "ty_not_opened": "لو واتساب مفتحش، اضغط الزرار اللي فوق.",
        "ty_back": "الرجوع إلى {p}", "ty_back_generic": "الرجوع للموقع",
        "wa_msg": "مرحبًا، سجّلت بياناتي على الموقع ومهتم بمشروع {p}{u}. ممكن الأسعار وخطط السداد؟",
        "wa_msg_generic": "مرحبًا، مهتم بمشاريع بالم هيلز. ممكن الأسعار وخطط السداد؟",
    },
    "en": {
        "dir": "ltr", "locale": "en_US",
        "nav": [("#units", "Units & Prices"), ("#about", "About"), ("#location", "Location"), ("#gallery", "Gallery"), ("#more", "Other projects")],
        "nav_cta": "Get prices",
        "menu": "Menu",
        "cta_main": "More details - WhatsApp",
        "cta_card": "Prices & payment plans",
        "down": "down payment", "years": "years installments", "from_m": "from (EGP million)",
        "offer_badge": "Up to {p}% discount on the {y}-year plan",
        "hero_note": "Prices are indicative and subject to change by the developer",
        "about_eyebrow": "About the project", "about_h": "About {t}", "about_p": "Everything you need to know in a minute",
        "units_eyebrow": "Units & Prices", "units_h": "Available units in {t}", "units_p": "Pick a unit type and get the price and payment plan on WhatsApp",
        "u_area": "Area", "u_deliv": "Delivery", "from": "From", "egp": "EGP", "sqm": "m²",
        "u_bua": "Built-up area", "u_land": "Land area", "price_req": "Price on request",
        "new_launch": "New launch", "fin_ff": "Fully finished", "fin_cs": "Core & Shell",
        "launch_eyebrow": "New Launch", "launch_h": "New phase: {n}", "launch_pay": "{d}% down payment, up to {y} years installments",
        "units_disc": "Prices and units shown above are indicative and may change or be updated at any time without prior notice, according to the developer's policy and unit availability. All images and promotional materials belong to Palm Hills Developments and are shown for illustration only.",
        "offer_h": "Up to <b>{p}%</b> discount on the {y}-year plan", "offer_p": "Or {d}% down payment with up to {yy} years installments — ask for the plan that suits you.",
        "plan_h": "<b>{d}%</b> down payment, up to <b>{yy} years</b> installments", "plan_p": "Ask about the payment plan that suits you and the latest available units.",
        "offer_cta": "Get the offer details",
        "loc_eyebrow": "Location", "loc_h": "{t} location", "loc_p": "Close to everything you need in West Cairo",
        "gal_eyebrow": "Photo Gallery", "gal_h": "Gallery", "gal_p": "A glimpse of {t}",
        "more_eyebrow": "More Palm Hills projects", "more_h": "Other Palm Hills projects", "more_p": "If {t} isn't the right fit, explore the other available Palm Hills projects",
        "more_link": "View project", "more_off": "Up to {p}% off",
        "final_h": "Get the latest <b>{t}</b> prices on WhatsApp", "final_lead": "Leave your number and we'll take you straight to WhatsApp.",
        "final_points": ["Currently available units with updated prices", "Active payment plans and discounts", "A direct reply from a property consultant"],
        "final_call": "Or call us: ", "final_form_h": "More details on WhatsApp",
        "f_title": "More details on WhatsApp", "f_sub": "Enter your name and number and we'll take you to WhatsApp right away",
        "f_name": "Name", "f_name_ph": "Your name", "f_name_err": "Please enter your name",
        "f_phone": "Mobile number", "f_phone_err": "That number doesn't look right — check the number and country code",
        "f_unit": "Unit type", "f_unit_ph": "Choose a unit type", "f_unit_any": "Not sure yet", "f_unit_err": "Please choose a unit type",
        "f_cc": "Country code", "f_cc_search": "Search country or code",
        "f_submit": "Continue to WhatsApp", "f_sending": "Redirecting…",
        "f_priv": 'By submitting you agree to our <a href="/privacy-policy" target="_blank" rel="noopener">Privacy Policy</a>',
        "no_country": "No results", "close": "Close",
        "stick_from": "From", "stick_cta": "Details - WhatsApp",
        "ck_title": "We respect your privacy 🍪",
        "ck_text": 'We use cookies to measure performance and improve your experience. Read our <a href="/privacy-policy">Privacy Policy</a>.',
        "ck_short": 'We use cookies to improve your experience. <a href="/privacy-policy">Privacy Policy</a>',
        "ck_ok": "Okay, got it", "ck_ok_short": "OK", "ck_aria": "Cookie notice",
        "ft_tag": "Connecting You to Egypt's Finest Properties",
        "ft_disc": "<strong>Disclaimer:</strong> This website is a marketing and informational platform owned and operated by an <strong>independent real estate broker</strong>. We are not the official developer or owner of any project shown. The site presents residential and investment opportunities from different developers for informational and marketing purposes only. All prices, payment plans and specifications are subject to change by the developers without prior notice, and the official developer of each project is the final reference. We are committed to full transparency and to protecting users' data and never sharing it with third parties without explicit consent.",
        "ft_rights": "All rights reserved", "ft_about": "About Us", "ft_priv": "Privacy Policy",
        "crumb_home": "Home",
        "home_seo_title": "VIBE Real Estate | Palm Hills Projects in 6th of October — Prices & Payment Plans 2026",
        "home_seo_desc": "VIBE Real Estate — an independent property broker. The latest Palm Hills projects in 6th of October: PX, Palm Parks, Crown Extension, Palm Hills One and Bamboo III, with prices and payment plans.",
        "home_nav": [("#projects", "Projects"), ("#more", "Other destinations"), ("#about", "About VIBE"), ("/about-us", "About Us")],
        "home_eyebrow": "Palm Hills Developments",
        "home_h1": "Palm Hills projects in 6th of October",
        "home_sub": "Apartments, town houses and villas by Palm Hills Developments — with prices and payment plans for every project",
        "home_stats": [("5", "projects available"), ("5%", "down payment from"), ("10", "years installments, up to")],
        "home_cta2": "Browse projects",
        "home_proj_eyebrow": "Our Projects", "home_proj_h": "Choose your project", "home_proj_p": "Each project has its own page with units, prices and location",
        "home_more_eyebrow": "More destinations", "home_more_h": "Other Palm Hills destinations", "home_more_p": "New Cairo, the New Capital and the North Coast",
        "home_more": [
            {"href": "/palm-hills-projects-east", "img": "east", "title": "Palm Hills East", "tag": "East Cairo", "text": "Palm Hills New Cairo, 97 Hills and VDLC in the New Capital. (Arabic page)"},
            {"href": "/hacienda-ras-al-hekma", "img": "hacienda", "title": "Hacienda Ras Al Hekma", "tag": "North Coast", "text": "Chalets, twin houses and villas in Ras El Hekma. (Arabic page)"},
        ],
        "home_explore": "Explore",
        "home_about_eyebrow": "About VIBE", "home_about_h": "Your compass in Egypt's property market",
        "home_about": ["VIBE Real Estate is an independent property broker specialised in Palm Hills Developments projects across West Cairo, East Cairo and the North Coast.",
                       "We present prices and payment plans exactly as the developer sets them, and help you compare and choose the home that fits your needs and budget — with no pressure."],
        "home_about_link": "More about us",
        "home_vibe": [("V", "Vision", "A clear view of the market and where it is heading."), ("I", "Investment", "Every recommendation made with an investor's mindset."), ("B", "Brokerage", "Over 20 years of experience in the Egyptian market."), ("E", "Excellence", "Accurate information and fast replies.")],
        "home_final_h": "Not sure which one? <b>Talk to us on WhatsApp</b>", "home_final_lead": "Tell us which project you're interested in and we'll send the prices and payment plans.",
        "f_project": "Project", "f_project_ph": "Choose a project", "f_project_err": "Please choose a project",
        "home_back": "the home page",
        "ty_seo_title": "Thank you – VIBE Real Estate",
        "ty_title": "Thanks for your interest", "ty_title_p": "Thanks for your interest in {p}",
        "ty_text": "One more step and the details are yours on WhatsApp.",
        "ty_points": ["Latest prices and available units", "Payment plans and current offers", "A property consultant to answer your questions"],
        "ty_title_generic": "Thanks for visiting", "ty_text_generic": "You can reach us on WhatsApp any time.",
        "ty_btn": "Open WhatsApp now", "ty_redirecting": "Redirecting you to WhatsApp in a moment…",
        "ty_not_opened": "If WhatsApp didn't open, tap the button above.",
        "ty_back": "Back to {p}", "ty_back_generic": "Back to the website",
        "wa_msg": "Hi, I just registered on the website and I'm interested in {p}{u}. Could you send me the prices and payment plans?",
        "wa_msg_generic": "Hi, I'm interested in Palm Hills projects. Could you send me the prices and payment plans?",
    },
}
