# -*- coding: utf-8 -*-
"""Single source of truth for the project landing pages.

Prices come from "Sales Availability 1 Oct 2026" (column Grand Total = full price before
any discount). Update the numbers here and run:  python3 tools/build.py
"""

SITE = {
    "domain": "https://viberealestatre.com",
    "brand": "VIBE Real Estate",
    "gtm": "GTM-PVRH422L",
    "wa": "201006140168",
    "tel": "01006140168",
    "tel_intl": "+201006140168",
    # Google Apps Script web-app URL (tools/apps-script/Code.gs). Leads are NOT stored until this is set.
    "endpoint": "",
}

# Order = order of the "other projects" carousel.
PROJECTS = {
    "px": {
        "name": "PX",                      # value sent to the sheet / dataLayer
        "title": "PX Compound",            # display name (English in both languages)
        "ready": True,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 13144000,
        "down": 5, "years": 10,
        "discount": {"pct": 40, "years": 6},
        "delivery": "2028",
        "types": {"ar": ["شقق", "تاون هاوس", "فيلات"], "en": ["Apartments", "Town Houses", "Villas"]},
        "img": "px",
        "hero_sub": {
            "ar": "على أعلى نقطة في بالم هيلز أكتوبر — شقق وتاون هاوس وفيلات من Palm Hills Developments",
            "en": "On the highest point of Palm Hills October — apartments, town houses and villas by Palm Hills Developments",
        },
        "seo": {
            "ar": {
                "title": "PX بالم هيلز أكتوبر | أسعار وخطط سداد PX Compound 2026 – VIBE Real Estate",
                "desc": "كمبوند PX من بالم هيلز في أكتوبر: شقق وتاون هاوس بمقدم 5% وتقسيط حتى 10 سنوات، وخصم يصل إلى 40%. الأسعار تبدأ من 13,144,000 جنيه. اعرف الوحدات المتاحة الآن.",
            },
            "en": {
                "title": "PX Palm Hills October | PX Compound Prices & Payment Plans 2026 – VIBE Real Estate",
                "desc": "PX by Palm Hills in 6th of October: apartments and town houses with 5% down payment, up to 10 years installments and up to 40% discount. Prices from EGP 13,144,000.",
            },
        },
        "about": {
            "ar": [
                "PX هو أحدث مشاريع Palm Hills Developments في غرب القاهرة، على أعلى نقطة في بالم هيلز أكتوبر، وده اللي بيدّي وحداته إطلالات مفتوحة على المنطقة كلها.",
                "المشروع على مساحة حوالي 370 فدان، والماستر بلان من تصميم Chapman Taylor العالمية، ومقسّم لمناطق سكنية مختلفة بين الشقق والتاون هاوس، مع نادي ومنطقة تجارية ومسارات مشي جوه الكمبوند.",
            ],
            "en": [
                "PX is Palm Hills Developments' newest community in West Cairo, set on the highest point of Palm Hills October — which gives its homes open views across the whole area.",
                "The project spans around 370 feddans with a master plan by Chapman Taylor, split into residential zones of apartments and town houses, with a clubhouse, a commercial hub and walking trails inside the compound.",
            ],
        },
        "facts": [
            {"v": "370", "ar": "فدان مساحة المشروع", "en": "feddans total area"},
            {"v": "2028", "ar": "بداية الاستلام", "en": "delivery starts"},
            {"v": "5%", "ar": "مقدم التعاقد", "en": "down payment"},
        ],
        "features": [
            {"ic": "mountain", "ar": ("أعلى نقطة في المنطقة", "إطلالات بانورامية مفتوحة من معظم الوحدات."),
             "en": ("Highest point in the area", "Open panoramic views from most homes.")},
            {"ic": "compass", "ar": ("ماستر بلان عالمي", "تصميم Chapman Taylor بمناطق سكنية منفصلة ومساحات مفتوحة."),
             "en": ("International master plan", "Designed by Chapman Taylor with distinct residential zones.")},
            {"ic": "dumbbell", "ar": ("كلوب هاوس ونادي رياضي", "جيم وملاعب ومرافق ترفيهية جوه المشروع."),
             "en": ("Clubhouse & sports", "Gym, courts and leisure facilities inside the project.")},
            {"ic": "store", "ar": ("منطقة تجارية", "محلات ومطاعم وكافيهات على بعد خطوات من بيتك."),
             "en": ("Commercial hub", "Retail, dining and cafés a short walk from home.")},
            {"ic": "bicycle", "ar": ("مسارات مشي ودراجات", "تراكات وسط مساحات خضراء ومسطحات مائية."),
             "en": ("Jogging & cycling trails", "Tracks running through greenery and water features.")},
            {"ic": "shield", "ar": ("أمن وبوابات 24 ساعة", "كمبوند مغلق بحراسة وكاميرات مراقبة."),
             "en": ("24/7 gated security", "A gated community with guards and CCTV.")},
        ],
        "units": [
            {"name": "1 Bedroom Apartment", "sub": {"ar": "شقة غرفة نوم واحدة", "en": "One-bedroom apartment"},
             "area": "60 – 78", "price": 13144000, "badges": ["Typical", "Penthouse"], "imgs": ["hero", "view"]},
            {"name": "2 Bedroom Apartment", "sub": {"ar": "شقة غرفتين نوم", "en": "Two-bedroom apartment"},
             "area": "113 – 140", "price": 19809000, "badges": ["Typical", "Garden", "Penthouse"], "imgs": ["view", "hero"]},
            {"name": "3 Bedroom Apartment", "sub": {"ar": "شقة 3 غرف نوم", "en": "Three-bedroom apartment"},
             "area": "144 – 172", "price": 25419000, "badges": ["Typical", "Garden"], "imgs": ["hero", "view"]},
            {"name": "Town House", "sub": {"ar": "تاون هاوس — أرض من 212 م²", "en": "Town house — land from 212 m²"},
             "area": "201 – 214", "price": 28528000, "badges": ["Middle", "Corner"], "imgs": ["view", "hero"]},
        ],
        # New launch inside PX — not in the availability sheet. Source: palmhillsdev.com/px-by-palm-hills
        "launch": {
            "name": "Palm Gardens",
            "intro": {
                "ar": "مرحلة جديدة جوه PX من التاون هاوس المتشطب بالكامل والفيلات المستقلة، على ارتفاع 128 متر فوق سطح البحر.",
                "en": "A new phase inside PX: fully finished town houses and standalone villas, set 128 m above sea level.",
            },
            "down": 5, "years": "7.5",
            "units": [
                {"name": "Townhouse Middle", "sub": {"ar": "3 غرف نوم — غرفة ماستر + ناني", "en": "3 bedrooms — 1 master + nanny room"},
                 "bua": "201", "land": "212", "price": 32638000, "finish": "ff", "imgs": ["view", "hero"]},
                {"name": "Townhouse Corner", "sub": {"ar": "3 غرف نوم — غرفة ماستر + ناني", "en": "3 bedrooms — 1 master + nanny room"},
                 "bua": "211", "land": "216", "price": 34500000, "finish": "ff", "imgs": ["hero", "view"]},
                {"name": "Villa 4", "sub": {"ar": "4 غرف نوم — 2 ماستر + ناني وسائق", "en": "4 bedrooms — 2 master + nanny & driver"},
                 "bua": "240", "land": "282", "price": 37000000, "finish": "cs", "imgs": ["view", "hero"]},
                {"name": "Villa 3", "sub": {"ar": "4 غرف نوم — 2 ماستر + ناني وسائق", "en": "4 bedrooms — 2 master + nanny & driver"},
                 "bua": "246", "land": "299", "price": 38800000, "finish": "cs", "imgs": ["hero", "view"]},
                {"name": "Villa 1", "sub": {"ar": "4 غرف نوم — 3 ماستر + أسانسير", "en": "4 bedrooms — 3 master + elevator"},
                 "bua": "314", "land": "420 – 470", "price": 53000000, "finish": "cs", "imgs": ["view", "hero"]},
                {"name": "Villa 5", "sub": {"ar": "6 غرف نوم ماستر + أسانسير", "en": "6 master bedrooms + elevator"},
                 "bua": "428", "land": "545 – 596", "price": None, "finish": "cs", "imgs": ["hero", "view"]},
            ],
        },
        "location": {
            "text": {
                "ar": "PX في قلب بالم هيلز أكتوبر، ومتصل بأهم محاور غرب القاهرة، وحواليه كمبوندات بالم هيلز التانية زي ذا كراون وبالم باركس.",
                "en": "PX sits at the heart of Palm Hills October, connected to West Cairo's main roads and surrounded by Palm Hills communities such as The Crown and Palm Parks.",
            },
            "points": [
                {"b": {"ar": "وصلة دهشور", "en": "Dahshur Link"}, "s": {"ar": "مدخل مباشر للمشروع", "en": "Direct access to the project"}},
                {"b": {"ar": "محور 26 يوليو", "en": "26th of July Axis"}, "s": {"ar": "ربط سريع بالقاهرة والشيخ زايد", "en": "Fast link to Cairo and Sheikh Zayed"}},
                {"b": {"ar": "طريق الواحات", "en": "Wahat Road"}, "s": {"ar": "أقرب طريق للمحاور الجنوبية", "en": "Closest route to the southern corridors"}},
                {"b": {"ar": "Mall of Egypt", "en": "Mall of Egypt"}, "s": {"ar": "أقرب مركز تسوق وترفيه", "en": "Nearest shopping & entertainment"}},
                {"b": {"ar": "المتحف المصري الكبير", "en": "Grand Egyptian Museum"}, "s": {"ar": "وأهرامات الجيزة", "en": "and the Giza Pyramids"}},
                {"b": {"ar": "مدينة الإنتاج الإعلامي", "en": "Media Production City"}, "s": {"ar": "وجامعات ومدارس أكتوبر", "en": "plus October's universities & schools"}},
            ],
            "map": "masterplan",
            "map_cap": {"ar": "الماستر بلان — اضغط للتكبير", "en": "Master plan — tap to enlarge"},
        },
        "gallery": [
            {"img": "hero", "cap": {"ar": "PX Compound — واجهات المباني", "en": "PX Compound — building façades"}},
            {"img": "view", "cap": {"ar": "PX Compound — فيو المشروع", "en": "PX Compound — project view"}},
            {"img": "masterplan", "cap": {"ar": "PX Compound — الماستر بلان", "en": "PX Compound — master plan"}},
        ],
    },
    "palm-parks": {
        "name": "Palm Parks", "title": "Palm Parks", "ready": False,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 17807000, "down": 5, "years": 8, "discount": None, "delivery": "2029",
        "types": {"ar": ["شقق"], "en": ["Apartments"]}, "img": "palm-parks",
    },
    "crown-extension": {
        "name": "The Crown Extension", "title": "Crown Extension", "ready": False,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 30521000, "down": 5, "years": 8, "discount": {"pct": 30, "years": 5}, "delivery": "2030",
        "types": {"ar": ["Family Home", "توين هاوس"], "en": ["Family Homes", "Twin Houses"]}, "img": "crown-extension",
    },
    "palm-hills-one": {
        "name": "Palm Hills One", "title": "Palm Hills One", "ready": False,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 47549000, "down": 5, "years": 8, "discount": None, "delivery": "2030",
        "types": {"ar": ["تاون هاوس", "توين هاوس", "فيلات"], "en": ["Town Houses", "Twin Houses", "Villas"]}, "img": "palm-hills-one",
    },
    "bamboo-iii": {
        "name": "Bamboo III", "title": "Bamboo III", "ready": False,
        "area": {"ar": "أكتوبر", "en": "6th of October"},
        "price_from": 27457000, "down": 5, "years": 10, "discount": None, "delivery": "2029",
        "types": {"ar": ["Family Home", "تاون هاوس"], "en": ["Family Homes", "Town Houses"]}, "img": None,
    },
}

T = {
    "ar": {
        "dir": "rtl", "locale": "ar_EG",
        "nav": [("#units", "الوحدات والأسعار"), ("#about", "عن المشروع"), ("#location", "الموقع"), ("#gallery", "الصور"), ("#more", "مشاريع أخرى")],
        "nav_cta": "اعرف الأسعار",
        "menu": "القائمة",
        "cta_main": "تفاصيل أكثر - واتساب",
        "cta_card": "الأسعار وخطط السداد",
        "down": "مقدم", "years": "سنوات تقسيط", "from_m": "يبدأ من (مليون جنيه)",
        "offer_badge": "خصم يصل إلى {p}% مع تقسيط {y} سنوات",
        "hero_note": "الأسعار استرشادية وقابلة للتغيير حسب المطوّر",
        "about_eyebrow": "About the project", "about_h": "نبذة عن {t}", "about_p": "كل اللي محتاج تعرفه عن المشروع في دقيقة",
        "units_eyebrow": "Units & Prices", "units_h": "الوحدات المتاحة في {t}", "units_p": "اختار نوع الوحدة واعرف السعر وخطة السداد على واتساب",
        "u_area": "المساحة", "u_deliv": "الاستلام", "from": "تبدأ من", "egp": "جنيه", "sqm": "م²",
        "u_bua": "مساحة المباني", "u_land": "مساحة الأرض", "price_req": "السعر عند الطلب",
        "new_launch": "لونش جديد", "fin_ff": "متشطب بالكامل", "fin_cs": "Core & Shell",
        "launch_eyebrow": "New Launch", "launch_h": "مرحلة جديدة: {n}", "launch_pay": "مقدم {d}% وتقسيط حتى {y} سنوات",
        "units_disc": "الأسعار والوحدات المعروضة أعلاه استرشادية وقابلة للتغيير أو التحديث في أي وقت دون إشعار مسبق، حسب سياسة الشركة المطوّرة ومدى توافر الوحدات لديها. جميع الصور والمواد الترويجية تخص Palm Hills Developments وتُعرض بغرض التوضيح فقط.",
        "offer_h": "خصم يصل إلى <b>{p}%</b> مع تقسيط {y} سنوات", "offer_p": "أو مقدم {d}% وتقسيط حتى {yy} سنوات — اسأل عن الخطة الأنسب ليك.",
        "plan_h": "مقدم <b>{d}%</b> وتقسيط حتى <b>{yy} سنوات</b>", "plan_p": "اسأل عن خطة السداد الأنسب ليك وأحدث الوحدات المتاحة.",
        "offer_cta": "اعرف تفاصيل العرض",
        "loc_eyebrow": "Location", "loc_h": "موقع {t}", "loc_p": "قريب من كل اللي بتحتاجه في غرب القاهرة",
        "gal_eyebrow": "Photo Gallery", "gal_h": "معرض الصور", "gal_p": "لمحة من {t}",
        "more_eyebrow": "More Palm Hills projects", "more_h": "مشاريع بالم هيلز التانية", "more_p": "لو {t} مش الأنسب ليك، شوف باقي مشاريع بالم هيلز المتاحة",
        "more_link": "تفاصيل المشروع", "more_off": "خصم حتى {p}%",
        "final_h": "اعرف أحدث أسعار <b>{t}</b> على واتساب", "final_lead": "سجّل رقمك وهنحوّلك على واتساب في نفس اللحظة.",
        "final_points": ["الوحدات المتاحة حاليًا بالأسعار المحدّثة", "خطط السداد والخصومات السارية", "رد مباشر من مستشار عقاري"],
        "final_call": "أو كلّمنا: ", "final_form_h": "تفاصيل أكثر على واتساب",
        "f_title": "تفاصيل أكثر على واتساب", "f_sub": "اكتب اسمك ورقمك وهنحوّلك على واتساب فورًا",
        "f_name": "الاسم", "f_name_ph": "اسمك", "f_name_err": "اكتب اسمك من فضلك",
        "f_phone": "رقم الموبايل", "f_phone_err": "الرقم مش صحيح — راجع الرقم وكود الدولة",
        "f_unit": "نوع الوحدة", "f_unit_ph": "اختار نوع الوحدة", "f_unit_any": "لسه مش محدد", "f_unit_err": "اختار نوع الوحدة",
        "f_cc": "كود الدولة", "f_cc_search": "دوّر على الدولة أو الكود",
        "f_submit": "تحويل إلى واتساب", "f_sending": "جاري التحويل…",
        "f_priv": 'بتسجيلك أنت موافق على <a href="/privacy-policy" target="_blank" rel="noopener">سياسة الخصوصية</a>',
        "no_country": "مفيش نتايج", "close": "إغلاق",
        "stick_from": "يبدأ من", "stick_cta": "تفاصيل - واتساب",
        "ck_title": "نحترم خصوصيتك 🍪",
        "ck_text": 'بنستخدم ملفات تعريف الارتباط (Cookies) لتتبع الأداء وتحسين تجربتك على الموقع. للمزيد اطّلع على <a href="/privacy-policy">سياسة الخصوصية</a>.',
        "ck_ok": "موافق، تمام", "ck_aria": "إشعار ملفات تعريف الارتباط",
        "ft_tag": "Connecting You to Egypt's Finest Properties",
        "ft_disc": "<strong>إخلاء مسؤولية:</strong> هذا الموقع عبارة عن منصة إعلامية وتسويقية مملوكة وتُدار بواسطة <strong>وسيط عقاري مستقل</strong>، ولسنا المطور الرسمي أو المالك لأي من المشاريع المعروضة. يهدف الموقع إلى عرض وتسويق الفرص السكنية والاستثمارية المتاحة من مطورين عقاريين مختلفين وذلك لأغراض تعريفية وتسويقية فقط. جميع الأسعار وخطط السداد والمواصفات المعروضة قابلة للتغيير من قِبل المطورين دون إشعار مسبق، والمرجع النهائي هو المطور الرسمي لكل مشروع. نلتزم بالشفافية الكاملة وبحماية خصوصية بيانات المستخدمين وعدم مشاركتها مع أي طرف ثالث دون موافقة صريحة.",
        "ft_rights": "جميع الحقوق محفوظة", "ft_about": "About Us", "ft_priv": "سياسة الخصوصية",
        "crumb_home": "الرئيسية",
        "ty_seo_title": "شكرًا لتسجيلك – VIBE Real Estate",
        "ty_title": "شكرًا لاهتمامك", "ty_title_p": "شكرًا لاهتمامك بـ {p}",
        "ty_text": "خطوة واحدة وتوصلك التفاصيل على واتساب.",
        "ty_points": ["أحدث الأسعار والوحدات المتاحة", "خطط السداد والعروض الحالية", "مستشار عقاري يرد على كل أسئلتك"],
        "ty_title_generic": "شكرًا لزيارتك", "ty_text_generic": "تقدر تتواصل معانا على واتساب في أي وقت.",
        "ty_btn": "افتح واتساب الآن", "ty_redirecting": "هنحوّلك على واتساب خلال ثواني…",
        "ty_not_opened": "لو واتساب مفتحش، اضغط الزرار اللي فوق.",
        "ty_back": "الرجوع إلى {p}", "ty_back_generic": "الرجوع للموقع",
        "wa_msg": "مرحبًا، سجّلت بياناتي على الموقع ومهتم بمشروع {p}{u}. ممكن الأسعار وخطط السداد؟",
        "wa_msg_generic": "مرحبًا، مهتم بمشاريع بالم هيلز. ممكن الأسعار وخطط السداد؟",
    },
    "en": {
        "dir": "ltr", "locale": "en_US",
        "nav": [("#units", "Units & Prices"), ("#about", "About"), ("#location", "Location"), ("#gallery", "Gallery"), ("#more", "Other projects")],
        "nav_cta": "Get prices",
        "menu": "Menu",
        "cta_main": "More details - WhatsApp",
        "cta_card": "Prices & payment plans",
        "down": "down payment", "years": "years installments", "from_m": "from (EGP million)",
        "offer_badge": "Up to {p}% discount on the {y}-year plan",
        "hero_note": "Prices are indicative and subject to change by the developer",
        "about_eyebrow": "About the project", "about_h": "About {t}", "about_p": "Everything you need to know in a minute",
        "units_eyebrow": "Units & Prices", "units_h": "Available units in {t}", "units_p": "Pick a unit type and get the price and payment plan on WhatsApp",
        "u_area": "Area", "u_deliv": "Delivery", "from": "From", "egp": "EGP", "sqm": "m²",
        "u_bua": "Built-up area", "u_land": "Land area", "price_req": "Price on request",
        "new_launch": "New launch", "fin_ff": "Fully finished", "fin_cs": "Core & Shell",
        "launch_eyebrow": "New Launch", "launch_h": "New phase: {n}", "launch_pay": "{d}% down payment, up to {y} years installments",
        "units_disc": "Prices and units shown above are indicative and may change or be updated at any time without prior notice, according to the developer's policy and unit availability. All images and promotional materials belong to Palm Hills Developments and are shown for illustration only.",
        "offer_h": "Up to <b>{p}%</b> discount on the {y}-year plan", "offer_p": "Or {d}% down payment with up to {yy} years installments — ask for the plan that suits you.",
        "plan_h": "<b>{d}%</b> down payment, up to <b>{yy} years</b> installments", "plan_p": "Ask about the payment plan that suits you and the latest available units.",
        "offer_cta": "Get the offer details",
        "loc_eyebrow": "Location", "loc_h": "{t} location", "loc_p": "Close to everything you need in West Cairo",
        "gal_eyebrow": "Photo Gallery", "gal_h": "Gallery", "gal_p": "A glimpse of {t}",
        "more_eyebrow": "More Palm Hills projects", "more_h": "Other Palm Hills projects", "more_p": "If {t} isn't the right fit, explore the other available Palm Hills projects",
        "more_link": "View project", "more_off": "Up to {p}% off",
        "final_h": "Get the latest <b>{t}</b> prices on WhatsApp", "final_lead": "Leave your number and we'll take you straight to WhatsApp.",
        "final_points": ["Currently available units with updated prices", "Active payment plans and discounts", "A direct reply from a property consultant"],
        "final_call": "Or call us: ", "final_form_h": "More details on WhatsApp",
        "f_title": "More details on WhatsApp", "f_sub": "Enter your name and number and we'll take you to WhatsApp right away",
        "f_name": "Name", "f_name_ph": "Your name", "f_name_err": "Please enter your name",
        "f_phone": "Mobile number", "f_phone_err": "That number doesn't look right — check the number and country code",
        "f_unit": "Unit type", "f_unit_ph": "Choose a unit type", "f_unit_any": "Not sure yet", "f_unit_err": "Please choose a unit type",
        "f_cc": "Country code", "f_cc_search": "Search country or code",
        "f_submit": "Continue to WhatsApp", "f_sending": "Redirecting…",
        "f_priv": 'By submitting you agree to our <a href="/privacy-policy" target="_blank" rel="noopener">Privacy Policy</a>',
        "no_country": "No results", "close": "Close",
        "stick_from": "From", "stick_cta": "Details - WhatsApp",
        "ck_title": "We respect your privacy 🍪",
        "ck_text": 'We use cookies to measure performance and improve your experience. Read our <a href="/privacy-policy">Privacy Policy</a>.',
        "ck_ok": "Okay, got it", "ck_aria": "Cookie notice",
        "ft_tag": "Connecting You to Egypt's Finest Properties",
        "ft_disc": "<strong>Disclaimer:</strong> This website is a marketing and informational platform owned and operated by an <strong>independent real estate broker</strong>. We are not the official developer or owner of any project shown. The site presents residential and investment opportunities from different developers for informational and marketing purposes only. All prices, payment plans and specifications are subject to change by the developers without prior notice, and the official developer of each project is the final reference. We are committed to full transparency and to protecting users' data and never sharing it with third parties without explicit consent.",
        "ft_rights": "All rights reserved", "ft_about": "About Us", "ft_priv": "Privacy Policy",
        "crumb_home": "Home",
        "ty_seo_title": "Thank you – VIBE Real Estate",
        "ty_title": "Thanks for your interest", "ty_title_p": "Thanks for your interest in {p}",
        "ty_text": "One more step and the details are yours on WhatsApp.",
        "ty_points": ["Latest prices and available units", "Payment plans and current offers", "A property consultant to answer your questions"],
        "ty_title_generic": "Thanks for visiting", "ty_text_generic": "You can reach us on WhatsApp any time.",
        "ty_btn": "Open WhatsApp now", "ty_redirecting": "Redirecting you to WhatsApp in a moment…",
        "ty_not_opened": "If WhatsApp didn't open, tap the button above.",
        "ty_back": "Back to {p}", "ty_back_generic": "Back to the website",
        "wa_msg": "Hi, I just registered on the website and I'm interested in {p}{u}. Could you send me the prices and payment plans?",
        "wa_msg_generic": "Hi, I'm interested in Palm Hills projects. Could you send me the prices and payment plans?",
    },
}
